# MongoDB Atlas Configuration
spring.data.mongodb.uri=mongodb+srv://ashubh:shubh010xDmongodb@cluster01.khe8kxx.mongodb.net/smart_expense_tracker

# Server Configuration
server.port=8080

# Logging
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# Gemini API Key
gemini.api.key=AIzaSyBbeEMFLzZiVCdPYlDYm1B8Su18SNUDPwk